### ISSUE TITLE
Non ASCII characters garbled in unfurl response

### ISSUE THREAD

**Issue by vivekatro** [jacktuck/unfurl#29] opened 2018-06-14 06:51 UTC
https://unfurl.now.sh/?url=https://www.yahoo.co.jp
AL the Japanese chars are messed up.

**Comment by Jerczu** [comment] 2018-06-14 08:44
Pretty simple way to fix just use encodeURIComponent() when collecting strings and decodeURIComponent() when displaying them back this should preserve japanese characters.

**Comment by jacktuck** [comment] 2018-06-22 00:06
@vivekatro I (think) the issue is over at micro-unfurl see my PR https://github.com/beeman/micro-unfurl/pull/3

**Comment by beeman** [comment] 2018-06-22 03:53
Issue fixed by @jacktuck and deployed :)

**Comment by jacktuck** [comment] 2018-06-22 08:28
<3

**Comment by vivekatro** [comment] 2018-06-23 15:57
Thanks @jacktuck for fixing it quickly!

**Comment by beeman** [comment] 2018-06-27 13:29
![image](https://user-images.githubusercontent.com/36491/41977129-eaeb21ee-7a1e-11e8-903c-6daad443281b.png)
Should be fixed thanks to @jacktuck !

**Comment by jacktuck** [comment] 2018-06-29 10:54
@vivekatro Thanks for this i'll take a look this evening

**Comment by vivekatro** [comment] 2018-06-29 11:18
https://unfurl.now.sh/?url=https://www.rakuten.co.jp
breaks, I get a timeout error. but it used to work with `1.1.6`

**Comment by jacktuck** [comment] 2018-06-29 12:47
@vivekatro Default timeout is 2000ms and this site takes 8000ms for me, you can pass your own timeout, though.

**Comment by jacktuck** [comment] 2018-06-29 12:54
Mm actually 1.1.6 used request rather than node-fetch so it had a higher timeout. I'll make a change to match the old timeout i think too. Good find.

From request:  ```timeout - integer containing the number of milliseconds to wait for a server to send response headers (and start the response body) before aborting the request. Note that if the underlying TCP connection cannot be established, the OS-wide TCP connection timeout will overrule the timeout option (the default in Linux can be anywhere from 20-120 seconds).```

**Comment by vivekatro** [comment] 2018-07-11 15:21
Were you able to check on yahoo.co.jp unfurling missing ogp and Twitter in the new version?

**Comment by jacktuck** [comment] 2018-07-12 11:37
@vivekatro Not yet. I need to make a test demonstrating whats missing etc to make sure it doesn't regress again.

**Comment by jacktuck** [comment] 2018-09-20 15:36
@vivekatro Good spot on yahoo.co.jp. Just found the issue which was User-Agent was not being set properly in the new release.

I've fixed it on the newest prerelease of unfurl.js@2.x.x (see README first), let me know if you'd like me to patch 1.6.x too, it's trivial to do so.  :)

**Closed by jacktuck** 2018-09-20 15:36 UTC
Labels: bug
